# Generated by Django 3.2.6 on 2021-08-25 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='livelurl',
            new_name='liveurl',
        ),
    ]
